### ISSUE TITLE
url.URL escaped path not present in go 1.4 which AppEngine uses

### ISSUE THREAD

**Issue by crewjam** [goji/goji#14] opened 2016-01-18 13:13 UTC
I'm not sure what the version support targets are, but it appears that net/url:URL `EscapedPath()` is not present in go1.4 which is used by AppEngine. I'd be happy to work on a PR if you'd like.

**Comment by zenazn** [comment] 2016-01-18 21:34
This version of Goji is 1.5+, both for `EscapedPath` and because `go get goji.io` won't work in 1.4

**Comment by zenazn** [comment] 2016-01-27 04:52
I'm going to close this issue since Goji is working as intended, but if AppEngine continues to not support Go 1.5 for an extended period it might be worth maintaining a branch with hacked together 1.4 compatibility.

**Closed by zenazn** 2016-01-27 04:52 UTC

**Comment by keighl** [comment] 2016-03-15 12:11
GAE recently released a [go1.6beta runtime](https://groups.google.com/forum/#!topic/google-appengine-go/bY_OqNw2Qzo). I'm hoping it does the trick. 

```yaml
# app.yaml
api_version: go1.6beta
```

**Comment by keighl** [comment] 2016-03-15 12:26
... however, there's no 1.6 support in the SDK yet, so it can't be run locally.

**Comment by keighl** [comment] 2016-04-02 16:37
GAE 1.6 support arrived finally:

https://cloud.google.com/appengine/downloads#Google_App_Engine_SDK_for_Go
